name: Deploy and Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  deploy-and-publish:
    # Publish the packages (only when neither '-clip' nor '-demo' are in the tag)
    if: contains(github.event.release.tag_name, '-clip') == false && contains(github.event.release.tag_name, '-demo') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build

      - name: publish walrus connect package
        uses: JS-DevTools/npm-publish@v3
        id: walrus-connect
        with:
          access: public
          provenance: true
          token: ${{ secrets.NPM_TOKEN }}
          package: "packages/walrus-connect/package.json"
          strategy: upgrade

      - name: publish walrus wallet package
        uses: JS-DevTools/npm-publish@v3
        id: walrus-wallet
        with:
          access: public
          provenance: true
          token: ${{ secrets.NPM_TOKEN }}
          package: "packages/walrus-wallet/package.json"
          strategy: upgrade

  build_deploy_clip:
    # Frontend deployment for Clip (when '-clip' IS in the tag)
    if: contains(github.event.release.tag_name, '-clip') == true
    uses: zktx-io/walrus-sites-provenance/.github/workflows/deploy_with_slsa3.yml@ca8d8b691bef986d443c6c485bd119afd19b1dcd # v0.6.2
    with:
      working-directory: './packages/clip'
    secrets:
      GIT_SIGNER_PIN: ${{ secrets.GIT_SIGNER_PIN }}

  build_deploy_demo:
    # Frontend deployment for Demo (when '-demo' IS in the tag)
    if: contains(github.event.release.tag_name, '-demo') == true
    uses: zktx-io/walrus-sites-provenance/.github/workflows/deploy_with_slsa3.yml@ca8d8b691bef986d443c6c485bd119afd19b1dcd # v0.6.2
    with:
      working-directory: './packages/demo'
    secrets:
      GIT_SIGNER_PIN: ${{ secrets.GIT_SIGNER_PIN }}
